/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views;

import java.awt.BorderLayout;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ni.edu.uni.programacion.backend.pojo.Vehicle;
import ni.edu.uni.programacion.controllers.PnlVehicleController;
import ni.edu.uni.programacion.controllers.PnlViewVehicleController;
import ni.edu.uni.programacion.views.models.VehicleTableModel;
import ni.edu.uni.programacion.views.panels.PnlViewVehicles;

/**
 *
 * @author Sistemas-05
 */
public class InternalFView extends javax.swing.JInternalFrame {
    
    private PnlViewVehicles pnlViewVehicles;
    private PnlViewVehicleController pnlViewVehicleController;
    private DefaultTableModel tableModel;
    private VehicleTableModel vehicleTbl;
    private List<Vehicle> data;
    private final String[] columnNames = null;
    
    /**
     * Creates new form IFrmVehicle
     */
    public InternalFView() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("View Vehicles");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.BorderLayout());
        pnlViewVehicles = new PnlViewVehicles();
        pnlViewVehicleController = new PnlViewVehicleController(pnlViewVehicles);

        pnlContent.add(pnlViewVehicles, BorderLayout.CENTER);
        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 758, 548);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        DlgAppVehicle vehicleDiag;
        vehicleDiag = new DlgAppVehicle(null, true);
        vehicleDiag.setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        vehicleTbl = new VehicleTableModel(data, columnNames);

        String info[] = new String[vehicleTbl.getColumnCount()];
        pnlViewVehicles = new PnlViewVehicles();
        pnlViewVehicleController = new PnlViewVehicleController(pnlViewVehicles);

        pnlViewVehicleController.getTblViewModel();

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        pnlViewVehicles = new PnlViewVehicles();
        pnlViewVehicleController = new PnlViewVehicleController(pnlViewVehicles);
        
        try { 
            pnlViewVehicleController.loadTable();
            tableModel = (DefaultTableModel)pnlViewVehicles.getTblViewVehicle().getModel();
            tableModel.removeRow(pnlViewVehicles.getTblViewVehicle().getSelectedRow());
        } catch (IOException ex) {
            Logger.getLogger(InternalFView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
       
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
